version: '3'

networks:
  web_net:
    external: true
    driver: bridge

volumes:
  minio_data:

services:
  minio:
    image: minio/minio:RELEASE.2024-07-16T23-46-41Z
    hostname: minio
    restart: ${RESTART_POLICY}
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ACCESS_KEY: ${ACCESS_KEY}
      MINIO_SECRET_KEY: ${SECRET_KEY}
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    networks:
      - web_net
    ports:
      - 9000:9000
      - 9001:9001
