---
- hosts: minio-servers
  become: true
  gather_facts: true
  name: setup active-active replication minio with docker compose 
  roles:
    - { role: roles/preparing, become: True, tags: preparing }
    - { role: roles/docker, bcome: True, tags: docker_setup }
    - { role: roles/minio, become: True, tags: minio }
